"""The read-only demo workspace.

What this is
------------

A snapshot of one seeded workspace, generated by :mod:`scripts.seed_demo` through the
**real** services and the real comparison engine, committed as JSON beside this file,
and served verbatim at ``GET /demo/workspace``.

Why a snapshot rather than a demo database
------------------------------------------

Two reasons, and the first is the one that matters.

**A visitor must never see somebody else's data.** A live endpoint would have to read
a workspace out of whatever database the deployment is pointed at. If the operator
ran the seed against a real workspace, or simply pointed the demo at the first RFQ
they found, an anonymous visitor could read real supplier names, real prices and real
contact addresses. A committed file cannot do that: whatever is in it is what a
reviewer read in the diff.

**It cannot be abused into a write.** There is no database session in this feature,
no token is issued, and every route is a GET. Read-only is a property of the route
table, not a promise the front end is trusted to keep.

Shape
-----

The payload is deliberately *the same shapes the authenticated API returns* — the
contents of ``GET /rfqs/{id}/overview`` for each RFQ, plus the taxonomy from
``GET /meta/options`` and a small dashboard summary. That is what lets the demo reuse
the real presentational components instead of a parallel set written for show, and it
means the demo cannot drift into showing something the product does not produce.

Regenerating it
---------------

    python -m scripts.seed_demo --reset --run-scheduler --dump-demo

The seed refuses to dump a workspace that is not the fictional demo account, and
every address and token it writes is scrubbed regardless — see
:func:`scripts.seed_demo.sanitise_for_demo`.
"""

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.core.config import settings
from app.core.exceptions import NotFoundError

logger = logging.getLogger(__name__)

#: Where the committed snapshot lives. Beside this module so it travels with the
#: code and needs no configuration to find.
WORKSPACE_FILE = Path(__file__).with_name("workspace.json")

#: Shown by the demo pages. Kept in the payload as well as the front end so the
#: wording cannot drift between the two.
DISCLAIMER = (
    "This is a sample workspace with invented suppliers and prices, generated by the "
    "real scoring engine. Every action is disabled: nothing here is saved, and no "
    "email is ever sent. Create an account to run your own tender."
)


@lru_cache(maxsize=1)
def load_workspace() -> dict[str, Any] | None:
    """The demo payload, or ``None`` when the deployment has no snapshot.

    Cached because the file never changes while the process is running, and a
    public endpoint should not hit the disk on every request.
    """

    if not settings.DEMO_MODE_ENABLED:
        return None

    if not WORKSPACE_FILE.exists():
        logger.warning(
            "Demo mode is enabled but %s is missing; /demo/workspace will 404. "
            "Generate it with: python -m scripts.seed_demo --dump-demo",
            WORKSPACE_FILE.name,
        )
        return None

    try:
        with WORKSPACE_FILE.open(encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError):
        # A corrupt snapshot must not take the API down with it: the demo is a
        # convenience, and every authenticated route is unaffected.
        logger.exception("Could not read the demo workspace at %s", WORKSPACE_FILE)
        return None


def get_workspace() -> dict[str, Any]:
    """The payload, or a 404 that explains how to create it."""

    workspace = load_workspace()

    if workspace is None:
        raise NotFoundError(
            "This deployment has no demo workspace. "
            "Run: python -m scripts.seed_demo --dump-demo"
        )

    return workspace
