"""workspace audit log

One new table. The body is generated — regenerate it with
``alembic revision --autogenerate`` rather than hand-editing the DDL, and let CI's
``alembic check`` step prove the migration and the models still agree (the same rule
as the initial schema).

Three things about ``audit_entries`` that are load-bearing rather than incidental:

* **``rfq_id`` is a plain integer with no foreign key, and that is deliberate.** A
  constraint with ``ON DELETE SET NULL`` would let deleting an RFQ *rewrite a column
  of this table* — mutation of history, which is the one thing it promises not to
  allow — and the two engines disagree about it anyway: PostgreSQL clears the
  reference while SQLite leaves it dangling, because SQLite only enforces foreign
  keys when they are switched on and this application does not switch them on. A
  plain integer behaves identically everywhere and cannot be touched by another
  table's lifecycle. The ``rfq_number`` and ``item_name`` snapshots beside it are
  what make a dangling reference harmless.
* **``user_id`` is ``ON DELETE CASCADE``.** The log belongs to a workspace, and
  removing the workspace removes its log — the one deletion that is supposed to take
  the entries with it. It is indexed first because every read filters on it, and the
  four columns the audit page filters by (``action``, ``actor_type``,
  ``entity_type``, ``rfq_id``) are indexed alongside it.
* **The rows are never updated.** That is enforced in the application by a SQLAlchemy
  ``before_update`` listener (see ``app/features/audit/model.py``), not by the
  schema: the database-level equivalent would be a trigger, which is more machinery
  than this needs and does not travel between SQLite and PostgreSQL.

Revision ID: dd1b34283762
Revises: f1de0d1828be
Create Date: 2026-09-29 22:37:50.526140

"""
from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd1b34283762'
down_revision: Union[str, None] = 'f1de0d1828be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=True),
    sa.Column('rfq_number', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), server_default='buyer', nullable=False),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_rfq_number'), ['rfq_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_rfq_number'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_actor_type'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_action'))

    op.drop_table('audit_entries')
    # ### end Alembic commands ###
