"""initial schema

Revision ID: 891cfb2e4072
Revises: 
Create Date: 2026-09-18 22:50:50.478205

"""
from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


revision: str = '891cfb2e4072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rfq_number', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.String(length=1000), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=32), server_default='pcs', nullable=False),
    sa.Column('delivery_expectation', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('incoterms', sa.String(length=16), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('buyer_company', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfqs_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_rfq_number'), ['rfq_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfqs_user_id'), ['user_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('risk_rating', sa.String(length=16), server_default='low', nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contact_email', name='uq_supplier_user_email')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_user_id'), ['user_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reminder_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'supplier_id', name='uq_invitation_rfq_supplier')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), server_default='no_response', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('llm_generated', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('requested_fields', sa.JSON(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=32), server_default='scheduler', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_invitation_id'), ['invitation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=2000), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), server_default='pcs', nullable=False),
    sa.Column('incoterms', sa.String(length=16), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('validity_date', sa.Date(), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duties', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_currency', sa.String(length=10), nullable=True),
    sa.Column('normalized_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('normalized_incoterms', sa.String(length=16), nullable=True),
    sa.Column('normalized_total_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('cost_breakdown', sa.JSON(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('completeness', sa.String(length=16), server_default='complete', nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('unparsed_notes', sa.String(length=4000), nullable=True),
    sa.Column('blocking_question', sa.String(length=1000), nullable=True),
    sa.Column('parse_confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_quotes_completeness'), ['completeness'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_invitation_id'), ['invitation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_reference_number'), ['reference_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_quotes_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('base_incoterms', sa.String(length=16), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('fx_rates', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('recommended_quote_id', sa.Integer(), nullable=True),
    sa.Column('backup_quote_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('is_conclusive', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('computed_by', sa.String(length=32), server_default='engine', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_rfq_id'), ['rfq_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_email', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=16), server_default='approved', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recommended_quote_id', sa.Integer(), nullable=True),
    sa.Column('overrode_recommendation', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('awarded_total_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('awarded_currency', sa.String(length=10), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['supplier_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_comparison_id'), ['comparison_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_rfq_id'), ['rfq_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_quote_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_decision'))
        batch_op.drop_index(batch_op.f('ix_approvals_comparison_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_is_current'))
        batch_op.drop_index(batch_op.f('ix_comparisons_id'))

    op.drop_table('comparisons')
    with op.batch_alter_table('supplier_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_reference_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_quotes_completeness'))

    op.drop_table('supplier_quotes')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_status'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_sent_at'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_kind'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_invitation_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_id'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_status'))
        batch_op.drop_index(batch_op.f('ix_invitations_rfq_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_expires_at'))

    op.drop_table('invitations')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_user_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfqs_user_id'))
        batch_op.drop_index(batch_op.f('ix_rfqs_status'))
        batch_op.drop_index(batch_op.f('ix_rfqs_rfq_number'))
        batch_op.drop_index(batch_op.f('ix_rfqs_id'))
        batch_op.drop_index(batch_op.f('ix_rfqs_deadline'))

    op.drop_table('rfqs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
