#!/usr/bin/env python3
"""Draw the browser icon both web apps ship, and write every file format it needs.

Run with ``--write`` after changing the mark, or with ``--check`` to prove the
committed files still match the drawing (CI runs the check, so an icon edit that
forgets to regenerate fails the build instead of shipping two different logos).

Why a generator rather than four hand-made files
------------------------------------------------
A favicon is not one file. A browser wants an SVG if it can read one and a
multi-resolution ``.ico`` if it cannot; iOS wants a 180 px PNG with an opaque
background, because it applies its own mask and a transparent tile comes out with
black corners; and every browser requests ``/favicon.ico`` by default even when the
page declares no icon at all. Four files, one mark. Hand-drawing them means three
of them are wrong the first time the mark changes, and nothing catches it — which is
exactly what had happened here: the buyer dashboard pointed at Vite's template logo,
``/vite.svg``, and the file did not exist, so the tab showed a blank page icon while
the supplier form carried a different mark in a data URI.

So the geometry is written down once, in :data:`BARS` and :data:`TILE_RADIUS`, on a
32-unit grid. The SVG is generated from it and the rasters are *drawn* from it, pixel
by pixel, with 4×4 supersampling for the curves. Two consequences worth stating: the
output is byte-identical on every machine, and there is no image library involved —
Pillow, and anything that rasterises SVG, is at least one more dependency than this
job is worth. ``zlib`` and ``struct`` from the standard library are enough to write a
PNG and to write a 32-bit ``.ico`` by hand.

The mark
--------
Three ascending bars on a rounded indigo tile: prices, ranked. It reads at 16 px,
which is the only size that really matters, and it says what the product does
(compare quotes, in order) rather than what every other app says (a check, a
document, a magnifying glass). The colours are the app's own ``--primary`` pair from
``frontend/src/index.css``, so the tab matches the buttons.
"""

from __future__ import annotations

import argparse
import struct
import sys
import zlib
from pathlib import Path

#: Everything below is expressed on this square grid and scaled to the output size,
#: so the SVG and the rasters can never disagree about proportions.
GRID = 32.0

#: Corner radius of the tile, in grid units. About 22% of the side, which is the
#: proportion an operating system uses for its own app icons.
TILE_RADIUS = 7.0

#: Top-left and bottom-right of the tile's diagonal gradient. The app's ``--primary``
#: is ``#5b5ef0``; the mark is a shade lighter at the top-left and darker at the
#: bottom-right so the tile does not read as a flat swatch at small sizes.
GRADIENT_START = (0x6A, 0x6D, 0xF5)
GRADIENT_END = (0x4D, 0x50, 0xE0)

#: The mark: ``(x, y, width, height)`` for each bar, all standing on ``y = 24``.
#: Each bar is drawn with fully rounded ends, so a 4-unit bar is a 4-unit-wide pill.
BARS = (
    (8.0, 17.0, 4.0, 7.0),
    (14.0, 13.0, 4.0, 11.0),
    (20.0, 9.0, 4.0, 15.0),
)

#: Resolutions inside ``favicon.ico``. 16 is the browser tab, 32 the taskbar and
#: bookmark bar, 48 the Windows desktop shortcut.
ICO_SIZES = (16, 32, 48)

#: iOS home-screen icon. 180 px is the largest size any current iPhone asks for.
APPLE_TOUCH_SIZE = 180

#: Samples per axis per pixel. Four is where the tile's corners stop looking stepped
#: without the generator becoming slow enough to notice.
SUPERSAMPLE = 4

#: Where the two applications keep static files. Vite copies ``public/`` verbatim
#: into ``dist/``, and both Render static sites publish ``dist/``, so a file here is
#: served from the site root.
APP_DIRECTORIES = ("frontend", "public_form")

SVG_NAME = "favicon.svg"
ICO_NAME = "favicon.ico"
APPLE_NAME = "apple-touch-icon.png"

SVG = f"""\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" role="img" aria-label="Supplier Quote Autopilot">
  <!-- Generated by scripts/make_favicons.py — see that file for the geometry and
       the reason this is generated rather than drawn by hand. -->
  <title>Supplier Quote Autopilot</title>
  <defs>
    <linearGradient id="tile" x1="0" y1="0" x2="32" y2="32" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#{GRADIENT_START[0]:02x}{GRADIENT_START[1]:02x}{GRADIENT_START[2]:02x}"/>
      <stop offset="1" stop-color="#{GRADIENT_END[0]:02x}{GRADIENT_END[1]:02x}{GRADIENT_END[2]:02x}"/>
    </linearGradient>
  </defs>
  <rect width="32" height="32" rx="{TILE_RADIUS:g}" fill="url(#tile)"/>
  <g fill="#ffffff">
"""
for _x, _y, _w, _h in BARS:
    SVG += (
        f'    <rect x="{_x:g}" y="{_y:g}" width="{_w:g}" height="{_h:g}" '
        f'rx="{_w / 2:g}"/>\n'
    )
SVG += "  </g>\n</svg>\n"


# --------------------------------------------------------------------- geometry
def _inside_rounded_rect(
    x: float,
    y: float,
    left: float,
    top: float,
    width: float,
    height: float,
    radius: float,
) -> bool:
    """Is the point inside a rectangle with rounded corners?

    Clamp the point to the rectangle shrunk by the radius and compare distances:
    if it is inside that inner rectangle the point is inside, and otherwise the
    nearest corner is the only thing that can exclude it.
    """

    if x < left or x > left + width or y < top or y > top + height:
        return False

    nearest_x = min(max(x, left + radius), left + width - radius)
    nearest_y = min(max(y, top + radius), top + height - radius)
    dx = x - nearest_x
    dy = y - nearest_y

    return dx * dx + dy * dy <= radius * radius


def _bar_at(x: float, y: float) -> bool:
    return any(
        _inside_rounded_rect(x, y, left, top, width, height, width / 2)
        for left, top, width, height in BARS
    )


def _tile_colour(x: float, y: float) -> tuple[int, int, int]:
    """The gradient, sampled on the 32-unit grid."""

    position = min(1.0, max(0.0, (x + y) / (2 * GRID)))

    return tuple(
        round(start + (end - start) * position)
        for start, end in zip(GRADIENT_START, GRADIENT_END)
    )


def render(size: int, *, bleed: bool) -> list[bytes]:
    """Draw the mark at ``size`` px and return one RGBA byte row per pixel row.

    ``bleed`` fills the whole square with the gradient and drops the transparent
    corners. That is what iOS needs: it masks the home-screen icon itself, and a
    pre-rounded tile with transparent corners ends up ringed in black.
    """

    scale = size / GRID
    step = 1.0 / SUPERSAMPLE
    samples = SUPERSAMPLE * SUPERSAMPLE
    rows: list[bytes] = []

    for pixel_y in range(size):
        row = bytearray()

        for pixel_x in range(size):
            red = green = blue = 0
            covered = 0

            for sample_y in range(SUPERSAMPLE):
                for sample_x in range(SUPERSAMPLE):
                    # Sample at the centre of each subpixel, then convert from
                    # output pixels back onto the 32-unit grid.
                    x = (pixel_x + (sample_x + 0.5) * step) / scale
                    y = (pixel_y + (sample_y + 0.5) * step) / scale

                    if bleed:
                        inside = 0.0 <= x <= GRID and 0.0 <= y <= GRID
                    else:
                        inside = _inside_rounded_rect(
                            x, y, 0.0, 0.0, GRID, GRID, TILE_RADIUS
                        )

                    if not inside:
                        continue

                    if _bar_at(x, y):
                        sample = (255, 255, 255)
                    else:
                        sample = _tile_colour(x, y)

                    red += sample[0]
                    green += sample[1]
                    blue += sample[2]
                    covered += 1

            if covered == 0:
                row += b"\x00\x00\x00\x00"
                continue

            # Average the colour over the covered samples only, and keep the
            # coverage itself as alpha: that is what antialiases the corners.
            row += bytes(
                (
                    round(red / covered),
                    round(green / covered),
                    round(blue / covered),
                    round(covered * 255 / samples),
                )
            )

        rows.append(bytes(row))

    return rows


# ------------------------------------------------------------------ png writer
def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def png_bytes(size: int, rows: list[bytes]) -> bytes:
    """A truecolour-with-alpha PNG, written by hand.

    Colour type 6 (RGBA), bit depth 8, no interlacing, one filter byte per row —
    ``\x00`` (None), because the image is flat and filtered overhead would not earn
    its keep.
    """

    header = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    raw = b"".join(b"\x00" + row for row in rows)

    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", header)
        + _png_chunk(b"IDAT", zlib.compress(raw, 9))
        + _png_chunk(b"IEND", b"")
    )


# ------------------------------------------------------------------ ico writer
def _ico_bitmap(size: int, rows: list[bytes]) -> bytes:
    """One image inside the ``.ico``, as a 32-bit bottom-up DIB.

    The alternative — embedding a PNG in the ``.ico`` — is smaller and every browser
    since IE11 reads it, but the plain DIB is what the format was designed around and
    costs a few hundred bytes here. A 40-byte ``BITMAPINFOHEADER`` declares the height
    as twice the real height, because the DIB carries the colour bitmap *and* the
    legacy 1-bit mask; the mask is written as zeros, which tells Windows to use the
    alpha channel instead of punching anything out.
    """

    header = struct.pack(
        "<IiiHHIIiiII",
        40,  # biSize
        size,  # biWidth
        size * 2,  # biHeight — colour bitmap plus the AND mask
        1,  # biPlanes
        32,  # biBitCount
        0,  # biCompression — BI_RGB
        size * size * 4,  # biSizeImage
        0,  # biXPelsPerMeter
        0,  # biYPelsPerMeter
        0,  # biClrUsed
        0,  # biClrImportant
    )

    pixels = bytearray()

    # DIB rows run bottom to top, and the channels are BGRA rather than RGBA.
    for row in reversed(rows):
        for index in range(0, len(row), 4):
            red, green, blue, alpha = row[index : index + 4]
            pixels += bytes((blue, green, red, alpha))

    # Each mask row is 1 bit per pixel, padded out to a 4-byte boundary.
    mask_row = ((size + 31) // 32) * 4
    mask = bytes(mask_row * size)

    return header + bytes(pixels) + mask


def ico_bytes(images: list[tuple[int, list[bytes]]]) -> bytes:
    """An ``.ico`` holding every resolution, which is the whole point of the format.

    Windows picks the size it needs for the context — 16 px in a tab, 48 px on the
    desktop — and a single-size icon scales badly in the other two.
    """

    directory = struct.pack("<HHH", 0, 1, len(images))
    offset = 6 + 16 * len(images)
    entries = b""
    payloads = b""

    for size, rows in images:
        image = _ico_bitmap(size, rows)
        entries += struct.pack(
            "<BBBBHHII",
            size % 256,  # width, 0 meaning 256
            size % 256,  # height
            0,  # palette size — 0 for truecolour
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(image),
            offset,
        )
        payloads += image
        offset += len(image)

    return directory + entries + payloads


# ---------------------------------------------------------------------- output
def build() -> dict[str, bytes]:
    """Every file the generator owns, as ``repository-relative path -> bytes``."""

    ico = ico_bytes([(size, render(size, bleed=False)) for size in ICO_SIZES])
    apple = png_bytes(
        APPLE_TOUCH_SIZE, render(APPLE_TOUCH_SIZE, bleed=True)
    )
    svg = SVG.encode("utf-8")

    files: dict[str, bytes] = {}

    for app in APP_DIRECTORIES:
        files[f"{app}/public/{SVG_NAME}"] = svg
        files[f"{app}/public/{ICO_NAME}"] = ico
        files[f"{app}/public/{APPLE_NAME}"] = apple

    return files


def _normalise(data: bytes) -> bytes:
    """Compare text payloads independently of the checkout's line endings.

    ``.gitattributes`` sets ``* text=auto``, so the SVG is checked out with CRLF on
    Windows and LF everywhere else. The bytes are the same file either way, and a
    generator that failed its own check on the maintainer's laptop would be worse
    than useless.
    """

    return data.replace(b"\r\n", b"\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--write", action="store_true", help="write the icons into both apps"
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="verify the committed icons match this drawing; exit 1 if not",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="repository root (default: the directory containing this script)",
    )

    args = parser.parse_args(argv)

    root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parents[1]
    files = build()

    if args.write:
        for relative, data in files.items():
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(f"wrote {relative} ({len(data)} bytes)")

        return 0

    stale: list[str] = []
    missing: list[str] = []

    for relative, data in files.items():
        path = root / relative

        if not path.exists():
            missing.append(relative)
        elif _normalise(path.read_bytes()) != _normalise(data):
            stale.append(relative)

    if missing or stale:
        for relative in missing:
            print(f"MISSING {relative}", file=sys.stderr)

        for relative in stale:
            print(
                f"STALE   {relative} — regenerate with "
                f"`python scripts/make_favicons.py --write`",
                file=sys.stderr,
            )

        return 1

    print(f"{len(files)} icon file(s) match the drawing")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
